// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MaxSum struct {
	Sum       int   `json:"sum"`
	Positions []int `json:"positions"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}
